### ISSUE TITLE
sd-webui 1.6.0 启动报错

### ISSUE THREAD

**Issue by XiaoCC** [Artiprocher/sd-webui-fastblend#6]
sd-webui 1.6.0 启动报错

Traceback (most recent call last):
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\launch.py", line 48, in <module>
    main()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\launch.py", line 44, in main
    start()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\modules\launch_utils.py", line 436, in start
    webui.webui()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1858, in launch
    self.validate_queue_settings()
  File "D:\stable diffusion\sd-webui-aki-v4\sd-webui-aki-v4\py310\lib\site-packages\gradio\blocks.py", line 1690, in validate_queue_settings
    raise ValueError("Progress tracking requires queuing to be enabled.")
ValueError: Progress tracking requires queuing to be enabled.
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Artiprocher** [comment]
你好，你似乎用了某个整合包，这个整合包可能用了旧版 webui，根据 Github 中相关的[讨论](https://github.com/v8hid/infinite-zoom-automatic1111-webui/issues/33)，升级 stable-diffusion-webui 到最新版本可以解决这个问题。

**Comment by XiaoCC** [comment]
![image](https://github.com/Artiprocher/sd-webui-fastblend/assets/7299222/8c582f47-f902-42d0-a784-71dbee9931a7)
他是在重新安装最新版的之前有问题的扩展后解决的问题，说明不是webui版本的问题，我的webui已经是稳定版的最新版了1.6

**Comment by Artiprocher** [comment]
我更新了这个插件，移除了前端的进度条显示，只在终端显示进度条，现在应该不会有这个问题了。

**Comment by XiaoCC** [comment]
解决了 可以用谢谢
