### ISSUE TITLE
使用秋叶整合包时，运行会出现这个报错，望大佬解决。

### ISSUE THREAD

**Issue by LZLLAB** [Artiprocher/sd-webui-fastblend#7]
VAE weights loaded.
Traceback (most recent call last):
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\extensions\sd-webui-fastblend\scripts\api.py", line 650, in smooth_video
    FastModeRunner().run(frames_guide, frames_style, batch_size=batch_size, window_size=window_size, ebsynth_config=ebsynth_config, save_path=frames_path)
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\extensions\sd-webui-fastblend\scripts\api.py", line 417, in run
    table_l = table_manager.build_remapping_table(frames_guide, frames_style, patch_match_engine, batch_size, desc="Fast Mode Step 1/4")
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\extensions\sd-webui-fastblend\scripts\api.py", line 332, in build_remapping_table
    remapping_table = [[(frames_style[i], 1)] for i in range(n)]
  File "H:\SD_秋叶_4.4\sd-webui-aki\sd-webui-aki-v4.4\sd-webui-aki-v4.4\extensions\sd-webui-fastblend\scripts\api.py", line 332, in <listcomp>
    remapping_table = [[(frames_style[i], 1)] for i in range(n)]
IndexError: list index out of range
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by Artiprocher** [comment]
你好，请检查 guide 和 style 视频的帧数是否一致。目前我推测是前者帧数比后者多导致的，我将在后续的版本更新中对这种情况输出提示信息来引导用户

**Comment by Artiprocher** [comment]
@LZLLAB 我刚才更新了一个版本，在新版中，如果 guide 视频和 style 视频帧数不一致，那么较长的视频会自动被截断，并在终端给出提示信息，请更新到新版本，感谢您的反馈！
