### ISSUE TITLE
这个错误怎么搞

### ISSUE THREAD

**Issue by wasdfwef** [Artiprocher/sd-webui-fastblend#8]
Traceback (most recent call last):
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/mnt/workspace/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-fastblend/scripts/api.py", line 650, in smooth_video
    FastModeRunner().run(frames_guide, frames_style, batch_size=batch_size, window_size=window_size, ebsynth_config=ebsynth_config, save_path=frames_path)
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-fastblend/scripts/api.py", line 417, in run
    table_l = table_manager.build_remapping_table(frames_guide, frames_style, patch_match_engine, batch_size, desc="Fast Mode Step 1/4")
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-fastblend/scripts/api.py", line 332, in build_remapping_table
    remapping_table = [[(frames_style[i], 1)] for i in range(n)]
  File "/mnt/workspace/stable-diffusion-webui/extensions/sd-webui-fastblend/scripts/api.py", line 332, in <listcomp>
    remapping_table = [[(frames_style[i], 1)] for i in range(n)]
IndexError: list index out of range

**Comment by Artiprocher** [comment]
Hi, @wasdfwef . Please see [this issue](https://github.com/Artiprocher/sd-webui-fastblend/issues/7).

**Comment by Artiprocher** [comment]
I updated this extension just now. Please use the new version. Thanks.
