### ISSUE TITLE
出现这个错误，大佬看下

### ISSUE THREAD

**Issue by zerolizhen** [Artiprocher/sd-webui-fastblend#9]
Traceback (most recent call last):
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\cuda\compiler.py", line 689, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 159, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 171, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends\cuda\libs\nvrtc.pyx", line 89, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\AI相关\sd-webui-aki-v4.3\extensions\sd-webui-fastblend\scripts\api.py", line 650, in smooth_video
    FastModeRunner().run(frames_guide, frames_style, batch_size=batch_size, window_size=window_size, ebsynth_config=ebsynth_config, save_path=frames_path)
  File "D:\AI相关\sd-webui-aki-v4.3\extensions\sd-webui-fastblend\scripts\api.py", line 417, in run
    table_l = table_manager.build_remapping_table(frames_guide, frames_style, patch_match_engine, batch_size, desc="Fast Mode Step 1/4")
  File "D:\AI相关\sd-webui-aki-v4.3\extensions\sd-webui-fastblend\scripts\api.py", line 338, in build_remapping_table
    _, target_style = patch_match_engine.estimate_nnf(source_guide, target_guide, source_style)
  File "D:\AI相关\sd-webui-aki-v4.3\extensions\sd-webui-fastblend\scripts\api.py", line 293, in estimate_nnf
    nnf = self.initialize_nnf(source_guide.shape[0]) if level==0 else self.update_nnf(nnf, level)
  File "D:\AI相关\sd-webui-aki-v4.3\extensions\sd-webui-fastblend\scripts\api.py", line 256, in initialize_nnf
    cp.repeat(cp.arange(height), width).reshape(height, width),
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\_creation\ranges.py", line 60, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy\_core\_kernel.pyx", line 1372, in cupy._core._kernel.ufunc.__call__
  File "cupy\_core\_kernel.pyx", line 1399, in cupy._core._kernel.ufunc._get_ufunc_kernel
  File "cupy\_core\_kernel.pyx", line 1082, in cupy._core._kernel._get_ufunc_kernel
  File "cupy\_core\_kernel.pyx", line 94, in cupy._core._kernel._get_simple_elementwise_kernel
  File "cupy\_core\_kernel.pyx", line 82, in cupy._core._kernel._get_simple_elementwise_kernel_from_code
  File "cupy\_core\core.pyx", line 2251, in cupy._core.core.compile_with_cache
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\cuda\compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\cuda\compiler.py", line 574, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\cuda\compiler.py", line 322, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\cuda\compiler.py", line 306, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "D:\AI相关\sd-webui-aki-v4.3\python\lib\site-packages\cupy\cuda\compiler.py", line 708, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: C:\Users\zhen\AppData\Local\Temp\tmpan7fpidl\4b5e207b198d4c8b7b55dfedb23e7c407db9253c.cubin.cu(1): catastrophic error: cannot open source file "cupy/complex.cuh"

1 catastrophic error detected in the compilation of "C:\Users\zhen\AppData\Local\Temp\tmpan7fpidl\4b5e207b198d4c8b7b55dfedb23e7c407db9253c.cubin.cu".
Compilation terminated.

**Comment by Artiprocher** [comment]
这个错误来自 `cupy` 的编译过程，暂时不能通过更新 FastBlend 的代码解决。请在终端查看 CUDA 版本（按 win+r，输入 `cmd` 并按下 `enter` 键，在弹出的窗口内输入 `nvidia-smi`，看右上角）。目前已知 `cupy` 在 windows 系统上不支持 CUDA 12.2，且不支持 Compute Capability 小于 3.0 的显卡，更多兼容性信息请参考 `cupy` 的[官方文档](https://docs.cupy.dev/en/latest/install.html)。
